language: python
python:
- '3.6'
- '3.7'
- '3.8'
- '3.9'
- pypy3
cache: pip
install:
- pip install -r requirements-tests.txt
- pip install -r requirements.txt
- pip install coveralls
script:
- python -m pytest --junitxml ./reports/results.xml --cov-config .coveragerc --cov=src
  .
after_success:
- coveralls
deploy:
  provider: pypi
  user: mlasevich
  password:
    secure: FE6QWO+CIJv/oMRHCPdoIYtU1Iq+Evd30sGBAG66mw6dWmgJEBF8AYvnX0Q5+mlisePnXk4iCodeRdhMoj+AcvDgqakDjeoZ9dOy9Bpp88Y5uX5nk5yg8Y9VP4m9snb4k0JrPyARkCGO6chzdvBqDBFq4iaCi+tD2aByUpW6TSID7GRbCUAtUNd4XnA2lQG515J4NIE+cq8G7IGwiv7bk+R2RVU03fyIT18LfXQrbV+Z4hvZlTZMWNEOiFkHKo/JUgzKVYOhWD8D0otn29Ed4jxSMxKC1XFTzlNNnrYxtANiygFRD3OVk3bR1llQBkvHLwdIRqfATSei7JHrXaehojBmEtAiI0frfGFH8gc4M5a/o+lp+3a2a2+XOMvgHLlTXvMHseYDvBTIu1Z0w7Qz4lLYPcwFXnMV/ByVnGiDgoLOCAoZD1g2DX2kZZLWOdAi8SgPc7qz6+3Ium6tjjL8wUtI/1qXfbYStbDK1CtVeXgYlaFq8csx9zy6zBhpObiFfZAntaNN2q0PjupeZwpQQnMJ3cGB00/hazETtRhAxyMuZQhJ0YH/nnhNK/vqIufYC0MEqRKpKuXcPdl8nkw220OO9V98LqXMV57iW3HPlPvzS5CNkV+4GziOOS33+qnlH1y6Sw90ZyndyCq6EXPKE513eIPnQqOPXBzxQGkh4Bw=
  skip_existing: true
  distributions: sdist bdist_wheel
  on:
    tags: true
